<?php

namespace Games\GameBundle\Entity\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTeams()
    {
        $qb = $this->createQueryBuilder('g')
            ->select('g.hometeam')
            ->groupBy('g.hometeam');

        $hometeams = $qb->getQuery()->getArrayResult();
        $teams = [];
        foreach ($hometeams as $team) {
            $teams[$team['hometeam']] = $team['hometeam'];
        }
        return $teams;
    }
}