games_game_game:
    resource: "@GamesGameBundle/Controller/GameController.php"
    type:     annotation

games_game:
    resource: "@GamesGameBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
